version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins/Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
    driver: local
